package kaisenweb.kaisenweb.utils;

public enum TypeOfRequest {
    MOST_POPULAR_MOVIES,
    UPCOMING_MOVIES,
    TOP_RATED_MOVIES,
    NOW_PLAYING_MOVIES,
    SIMILAR_TO_MOVIES,
    MOST_POPULAR_TV_SHOWS,
    TOP_RATED_TV_SHOWS,
    ON_THE_AIR_TV_SHOWS,
    ON_THE_AIR_TODAY_TV_SHOWS
}
